/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myapplication_LifecycleActivity */

#ifndef _Included_com_example_administrator_myapplication_LifecycleActivity
#define _Included_com_example_administrator_myapplication_LifecycleActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myapplication_LifecycleActivity
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_myapplication_LifecycleActivity_getStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
